

Prepare:
	rm -f Output Source
	ln -sf $(ProjectBase)/DataPerformance/24131_RelativeTriggerTurnOn Source
	ln -sf $(ProjectBase)/MainAnalysis/GlobalSetting/GlobalSetting.dh .
	ln -sf /eos/cms/store/group/phys_heavyions/chenyi/PhysicsWorkspace/HIJetRAA2018/DataPerformance/24261_TriggerTurnOnBatchRun/ Output
	mkdir -p Log




