

default: DefaultSettings TAASettings SampleSettings JetIDSettings

DefaultSettings:
	bash SetBinning.sh
	bash SetGlobal.sh

SampleSettings:
	bash SetSample.sh

TAASettings:
	bash SetTAA.sh

JetIDSettings:
	bash SetJetID.sh


