

default: Prepare PlaceHolder

Prepare:
	ln -sf $(ProjectBase)/MainAnalysis/GlobalSetting/GlobalSetting.dh .

PlaceHolder:
	DHRemove GlobalSetting.dh PUBugCorrection
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R1_Centrality0to10   float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R1_Centrality10to30  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R1_Centrality30to50  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R1_Centrality50to90  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R2_Centrality0to10   float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R2_Centrality10to30  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R2_Centrality30to50  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R2_Centrality50to90  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R3_Centrality0to10   float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R3_Centrality10to30  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R3_Centrality30to50  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R3_Centrality50to90  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R4_Centrality0to10   float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R4_Centrality10to30  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R4_Centrality30to50  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R4_Centrality50to90  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R5_Centrality0to10   float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R5_Centrality10to30  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R5_Centrality30to50  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R5_Centrality50to90  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R6_Centrality0to10   float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R6_Centrality10to30  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R6_Centrality30to50  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R6_Centrality50to90  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R7_Centrality0to10   float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R7_Centrality10to30  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R7_Centrality30to50  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R7_Centrality50to90  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R8_Centrality0to10   float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R8_Centrality10to30  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R8_Centrality30to50  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R8_Centrality50to90  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R9_Centrality0to10   float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R9_Centrality10to30  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R9_Centrality30to50  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PbPbData_R9_Centrality50to90  float 1.04
	DHSet GlobalSetting.dh PUBugCorrection PPData_R1_CentralityInclusive float 1.00
	DHSet GlobalSetting.dh PUBugCorrection PPData_R2_CentralityInclusive float 1.00
	DHSet GlobalSetting.dh PUBugCorrection PPData_R3_CentralityInclusive float 1.00
	DHSet GlobalSetting.dh PUBugCorrection PPData_R4_CentralityInclusive float 1.00
	DHSet GlobalSetting.dh PUBugCorrection PPData_R5_CentralityInclusive float 1.00
	DHSet GlobalSetting.dh PUBugCorrection PPData_R6_CentralityInclusive float 1.00
	DHSet GlobalSetting.dh PUBugCorrection PPData_R7_CentralityInclusive float 1.00
	DHSet GlobalSetting.dh PUBugCorrection PPData_R8_CentralityInclusive float 1.00
	DHSet GlobalSetting.dh PUBugCorrection PPData_R9_CentralityInclusive float 1.00




